# Generated by Django 5.2 on 2025-04-10 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioPerfeccionamiento',
            fields=[
                ('id_estudioperfeccionamiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Estudio de Doctorado', 'Estudio de Doctorado'), ('Estudio de Maestría', 'Estudio de Maestría'), ('Pasantía', 'Pasantía'), ('Curso de Especialización', 'Curso de Especialización'), ('Certámenes Académicos', 'Certámenes Académicos'), ('Evento Académico', 'Evento Académico'), ('Estudio de Ofimática', 'Estudio de ofimática'), ('Estudio de Idioma', 'Estudio de Idioma')], max_length=100)),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/estudioperfeccionamiento/')),
            ],
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id_juez', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('fecha_evaluacion', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('orden', models.IntegerField()),
                ('cargo', models.CharField(choices=[('Juez Especializado', 'Juez Especializado o Mixto'), ('Juez de Paz Letrado', 'Juez de Paz Letrado'), ('Juez Superior', 'Juez Superior')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id_gradoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_gd', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('DOJ', 'Doctorado en especialidad jurídica'), ('DONJ', 'Doctorado en especialidad no jurídica'), ('MAJ', 'Maestría en especialidad jurídica'), ('MANJ', 'Maestría en especialidad no jurídica'), ('TINJ', 'Título en especialidad no jurídica')], max_length=5)),
                ('anio', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/gradoacademico/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id_eventoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/eventoacademico/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('id_estudioperfeccionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.estudioperfeccionamiento')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiosMagistratura',
            fields=[
                ('id_estudiomagistratura', models.AutoField(primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('nota', models.FloatField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/estudiosmagistratura/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='EstudioOfimatica',
            fields=[
                ('id_ofimatica', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('estudio', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/ofimatica/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('id_estudioperfeccionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.estudioperfeccionamiento')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='EstudioMaestria',
            fields=[
                ('id_estudiomaestria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('nota', models.FloatField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/estudiomaestria/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('id_estudioperfeccionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.estudioperfeccionamiento')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='EstudioIdioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('estudio', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/idioma/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('id_estudioperfeccionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.estudioperfeccionamiento')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='EstudioDoctorado',
            fields=[
                ('id_estudiodoctorado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('nota', models.FloatField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/estudiodoctado/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('id_estudioperfeccionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.estudioperfeccionamiento')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='Docencia',
            fields=[
                ('id_docencia', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=255)),
                ('universidad', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('horas', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/docencia/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='Distincion',
            fields=[
                ('id_distincion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/distincion/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='Demeritos',
            fields=[
                ('id_demerito', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('AMONESTACION', 'Amonestación'), ('MULTA', 'Multa'), ('SUSPENSION', 'Suspensión')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('puntaje', models.FloatField()),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='CursoEspecializacion',
            fields=[
                ('id_cursoespecializacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('horas', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/cursoespecializacion/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('id_estudioperfeccionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.estudioperfeccionamiento')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='CertamenAcademico',
            fields=[
                ('id_certamenacademico', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_participacion', models.CharField(choices=[('Expositor', 'Expositor'), ('Ponente', 'Ponente'), ('Panelista', 'Panelista')], max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=50)),
                ('anio', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/certamenacademico/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('id_estudioperfeccionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.estudioperfeccionamiento')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='Antiguedad',
            fields=[
                ('id_antiguedad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('puntaje', models.FloatField(default=0)),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='Pasantia',
            fields=[
                ('id_pasantia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=50)),
                ('anio', models.IntegerField()),
                ('nota', models.FloatField()),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/pasantia/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('id_estudioperfeccionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.estudioperfeccionamiento')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionJuridica',
            fields=[
                ('id_publicacionjuridica', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('LIBRO', 'Libro'), ('REVISTA', 'Revista'), ('MERITO', 'Publicación con mérito')], max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('puntaje', models.FloatField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='certificados/publicacionjuridica/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado')], default='PENDIENTE', max_length=10)),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
        migrations.CreateModel(
            name='PuntajeTotal',
            fields=[
                ('id_puntaje_total', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_antiguedad', models.FloatField(default=0)),
                ('puntaje_grado_academico', models.FloatField(default=0)),
                ('puntaje_estudios_magistratura', models.FloatField(default=0)),
                ('puntaje_estudios_doctorado', models.FloatField(default=0)),
                ('puntaje_estudios_maestria', models.FloatField(default=0)),
                ('puntaje_pasantia', models.FloatField(default=0)),
                ('puntaje_curso_especializacion', models.FloatField(default=0)),
                ('puntaje_certamen_academico', models.FloatField(default=0)),
                ('puntaje_evento_academico', models.FloatField(default=0)),
                ('puntaje_ofimatica', models.FloatField(default=0)),
                ('puntaje_idioma', models.FloatField(default=0)),
                ('puntaje_publicaciones', models.FloatField(default=0)),
                ('puntaje_distincion', models.FloatField(default=0)),
                ('puntaje_docencia', models.FloatField(default=0)),
                ('puntaje_demeritos', models.FloatField(default=0)),
                ('puntaje_total', models.FloatField(default=0)),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meritocracia.juez')),
            ],
        ),
    ]
