# Generated by Django 5.2 on 2025-04-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meritocracia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certamenacademico',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/certamenacademico/'),
        ),
        migrations.AddField(
            model_name='cursoespecializacion',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/cursoespecializacion/'),
        ),
        migrations.AddField(
            model_name='distincion',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/distincion/'),
        ),
        migrations.AddField(
            model_name='docencia',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/docencia/'),
        ),
        migrations.AddField(
            model_name='estudiodoctorado',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/estudiodoctado/'),
        ),
        migrations.AddField(
            model_name='estudioidioma',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/idioma/'),
        ),
        migrations.AddField(
            model_name='estudiomaestria',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/estudiomaestria/'),
        ),
        migrations.AddField(
            model_name='estudioofimatica',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/ofimatica/'),
        ),
        migrations.AddField(
            model_name='estudioperfeccionamiento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/estudioperfeccionamiento/'),
        ),
        migrations.AddField(
            model_name='estudiosmagistratura',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/estudiosmagistratura/'),
        ),
        migrations.AddField(
            model_name='eventoacademico',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/eventoacademico/'),
        ),
        migrations.AddField(
            model_name='gradoacademico',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/gradoacademico/'),
        ),
        migrations.AddField(
            model_name='pasantia',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/pasantia/'),
        ),
        migrations.AddField(
            model_name='publicacionjuridica',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='certificados/publicacionjuridica/'),
        ),
        migrations.AlterField(
            model_name='juez',
            name='cargo',
            field=models.CharField(choices=[('Juez Especializado', 'Juez Especializado o Mixto'), ('Juez de Paz Letrado', 'Juez de Paz Letrado'), ('Juez Superior', 'Juez Superior')], max_length=100),
        ),
    ]
